### ISSUE TITLE
Enchancement request on Youtube

### ISSUE THREAD

**Issue by david-morris** [pcwii/cpkodi-skill#22]
The youtube commands didn't work on my system, and I saw that you have been changing that lately.

Why not add a dependency to youtube_dl? Then you could use their API to fetch video entries:

```
ydl = youtube_dl.YoutubeDL(ydl_opts)
results = ydl.extract_info("ytsearch:<query string>")
```

and that way, if the Youtube API changes, you won't duplicate the youtube_dl team's work.

**Comment by pcwii** [comment]
Thanks for contributing. This is a good idea. I am also looking at https://github.com/HelloChatterbox/youtube_searcher as a dependancy since this is maintained by a Mycroft.ai contributer.

**Comment by pcwii** [comment]
refactored the youtube functions using the youtube_searcher. It appears to be working on my end, Let me know if it is working for you now.

**Comment by david-morris** [comment]
Great work!  I also see why a fresh install isn't the usual upgrade path for devs.  I haven't tested that the `manifest` changes worked, but I know it works when you pull in the dependency with `mycroft-pip`.
