### ISSUE TITLE
[Request] Add support for PVR

### ISSUE THREAD

**Issue by denics** [pcwii/cpkodi-skill#25]
Would it be possible to add support for PVR? like "play channel BBC" ?

**Comment by pcwii** [comment]
I do not run PVR on my kodi instance. Is there a client you would recommend for testing?

**Comment by denics** [comment]
Personally, being in France, I use https://github.com/aassif/pvr.freebox . For testing you can use the generic https://github.com/kodi-pvr/pvr.iptvsimple and you can see the list of commands in the interface https://github.com/xbmc/xbmc/blob/master/xbmc/addons/kodi-dev-kit/include/kodi/addon-instance/PVR.h

**Comment by david-morris** [comment]
I run PVR on my machine. 

I've found Kore's code for forming JSONRPC requests for groups and channels: https://github.com/xbmc/Kore/blob/6fd2a3b2d368170612e6b81286f01382b7b0c6aa/app/src/main/java/org/xbmc/kore/jsonrpc/method/PVR.java

If someone else wants to implement this, please comment here, I've got this on my todo list now.

**Comment by david-morris** [comment]
@denics you mentioned that you're in France, using PVR for French TV.  I'm in Germany, using PVR for German TV.  And I'm using this app in English.

If you're using this app in French, you should contribute your language files.  If you're using this app in English, how do you suggest someone opens a French or German PVR group or channel by name when the speech-to-text is listening for English words?

The easiest way of giving a channel a name is to add it to the Favourites and rename it.  Which I've just tested, that works, I can open PVR channels with my voice.

I'm going to see if I can find English language channels and get this working with those.

Getting this to work with foreign-to-mycroft languages would be a major project, not that I'm opposed to it. The `skill-audio-record` shows that there are ways of getting recordings for sending off for another language's speech recognition.  But unless you know something I don't, I think that should be a separate issue and quite a few pull requests, maybe even its own project.

**Comment by denics** [comment]
Hi @david-morris great tip! concerning the languages, I am working on the Italian translations as I am using Mycroft in Italian ;) I was wondering if the channels could be called by number, would that be possible?
like "Hey Mycroft, metti il canale 128" ("Hey Mycroft, play channel 128")

**Comment by david-morris** [comment]
Oh yeah, I'll do that, I didn't notice they had numbers.
