### ISSUE TITLE
[Request] License?

### ISSUE THREAD

**Issue by david-morris** [pcwii/cpkodi-skill#32]
I see that the old version of this project has GPL 3.0, which would be really great for this project since it's sitting on the mycroft-core repo which has a highly invested company involved.

Whatever license you choose, it'd be good to have clarity.

**Comment by pcwii** [comment]
I am honestly not concerned too much about the project licensing. Am good with GPL 3.0, really looking to do what I can to contribute to the community and it has been a great learning tool for me on python, so win-win. I appreciate your contribution to this project too! My bandwidth to work on these project is typically dictated by my full time work and family life.
Thanks
