### ISSUE TITLE
Crash while reading some PVR intent block in __init__.py

### ISSUE THREAD

**Issue by mardub1635** [pcwii/cpkodi-skill#38]
<img width="1280" alt="bug-cpkodi" src="https://user-images.githubusercontent.com/13570586/115577932-1df84900-a2c5-11eb-9f08-0eca59613482.png">
I installed cpkodi today on a new device but it crashed.

The command I ran to install it is:
mycroft-msm https://github.com/pcwii/cpkodi-skill.git

Here is the bug log on mycroft debug:

```
15:06:31.652 | INFO     |  6412 | mycroft.skills.skill_loader:_communicate_load_status:280 | Skill mycroft-configuration.mycroftai loaded successfully
 15:06:31.654 | INFO     |  6412 | mycroft.skills.skill_loader:load:114 | ATTEMPTING TO LOAD SKILL: cpkodi-skill.pcwii
~~~~kill.pcwii (SyntaxError('invalid syntax', ('/opt/mycroft/skills/cpkodi-skill.pcwii/__init__.py', 379, 32, '                if channel_no := self._match_adapt_regex(phrase, "ChannelNumber") is not None:\n')))
Traceback (most recent call last):
  File "/opt/mycroft/mycroft/skills/skill_loader.py", line 208, in _load_skill_source
    ('.py', 'rb', imp.PY_SOURCE)
  File "/usr/lib/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/mycroft/skills/cpkodi-skill.pcwii/__init__.py", line 379
    if channel_no := self._match_adapt_regex(phrase, "ChannelNumber") is not None:
                   ^
SyntaxError: invalid syntax
 15:06:31.670 | ERROR    |  6412 | mycroft.skills.skill_loader:_communicate_load_status:287 | Skill cpkodi-skill.pcwii failed to load 

```

This bug seem to disappear if I modify '__init__.py' and comment/remove the all function:
```
@intent_handler(IntentBuilder('').require("WatchKeyword").require("PVRKeyword").optionally("ChannelNumber"))                                                                                                   
def handle_channel(self, message):                                                                                                                                                                             
    if 'ChannelNumber' in message.data:                                                                                                                                                                        
        play_channel_number(self.kodi_path, int(message.data['ChannelNumber']))                                                                                                                                
        return
    if channel_no := self._match_adapt_regex(message.data['utterance'], "ChannelNumber") is not None:                                                                                                          
        self.dLOG("Adapt failed to recognize an optional regex.")                                                                                                                                              
        play_channel_number(self.kodi_path, int(channel_no))                                                                                                                                                   
        return                                                                                                                                                                                                 
    self.dLOG("Channel number not matched. Trying to find a channel name.")                                                                                                                                    
    channel_query = message.utterance_remainder()                                                                                                                                                              
    channels = find_channel(self.kodi_path, channel_query)                                                                                                                                                     
    if len(channels) == 0:                                                                                                                                                                                     
        self.speak_dialog('no.channel', data={'title':channel_query},                                                                                                                                          
                          expect_response=False,                                                                                                                                                               
                          wait=False)                                                                                                                                                                          
        return False
```
... but this is likely going to disable PVR support?

**Comment by david-morris** [comment]
Hey, I see what's going on here.  Thanks for raising this issue.
the `:=` operator was added in python 3.8.  You're using python 3.7.

There's two ways of handling this.  I'll make another post when I've thought about it a bit.

@pcwii , should we support 3.7 or encourage upgrades? @mardub1635 , how did you get Mycroft?  Github, a distro designed for running mycroft, or did you buy a device?

**Comment by mardub1635** [comment]
Hey @david-morris ,

I see! No the 'new' device is my raspberry pi 4 but via a docker image found on docker hub. And yes this docker image is like 10 month old:
https://hub.docker.com/r/mjkaye/mycroft-debian-slim/tags?page=1&ordering=last_updated
That might explain the outdated python 3.7 issue.
This might be an over specific issue indeed, I let you judge of that.

**Comment by david-morris** [comment]
Hey @mardub1635 , I don't think people with 10 month old docker images should have to figure out how to upgrade python inside a .venv.  I'll make a pull request about this tomorrow.

**Comment by mardub1635** [comment]
Thanks @david-morris  for the fast answer.  And yes the update of python in this docker is hard to do and tend to break mycroft itself. For now I keep the  PVR function commented and stay on my old version as the rest works fine.

**Comment by david-morris** [comment]
@mardub1635 the "play" keyword should still work for bringing up channels, just in case you were going to have a PVR voice party tonight.

**Comment by david-morris** [comment]
Hey @mardub1635 , could you check out my patch and see if it works for you? If you're confident with git and want to check it out before it gets merged, that would be useful, since I don't have python 3.7 on my machine.

**Comment by mardub1635** [comment]
Which branch name should I check out?

**Comment by david-morris** [comment]
@mardub1635 you'd have to `git stash` to temporarily put away your changes, `git remote add david-morris https://github.com/david-morris/cpkodi-skill.git` to tell git you want to refer to my repo, `git fetch david-morris master` to tell git to download my version into your history, and `git checkout david-morris/master` to switch to my version so you can run it.

If it doesn't work, you should be able to run `git checkout master` and then `git stash pop` to put your changes back on.

If it does work, make sure to `git checkout master` and `git pull` after the branch gets merged, to get back on the main version of the skill and keep it up to date.

Just for reference, you can `git fetch` an entire remote, but this is generally not what you want to do because on larger projects that will download a lot of stuff you don't need, and then show those options to you whenever you are checking out a branch.

**Comment by mardub1635** [comment]
Hi, I confirm pckodi loads correctly with your modification.
=== actions done ===

#cd in my dedicated skill folder
rm -r ./cpkodi-skill
git clone https://github.com/david-morris/cpkodi-skill.git
#Added a "print('TEST TEST TEST!! this is david-morris version ')" message inside the ./cpkodi-skill/\_\_init__.py file. This message appeared successfully on the debug prompt.
#tried several command such as "play the movie the nude vampire" "pause movie" "resume movie" all of them work fine and do not return errors.


====
I think you can merge the changes.

As for PVR itself:
PVR is not a functionality that I need. I am not even sure what it is made for, so when running an example of command from it I get an error. This error does not crash cpkodi or mycroft so it is fine for users like me. This bug might just be because of non-adapted settings on my side:
` 13:30:31.752 | INFO     |  1441 | Playback Control Skill | Audio service status: {}
{"id":1,"jsonrpc":"2.0","result":[{"playerid":1,"playertype":"internal","type":"video"}]}
 13:30:45.419 | INFO     |  1441 | cpkodi-skill.kodi_tools.PausePlayer:pause_all:24 | {"id":1,"jsonrpc":"2.0","result":{"speed":0}}
 13:31:06.477 | ERROR    |  1441 | mycroft.skills.mycroft_skill.mycroft_skill:on_error:835 | An error occurred while processing a request in CP Kodi Skill
Traceback (most recent call last):
  File "/opt/mycroft/mycroft/skills/mycroft_skill/event_container.py", line 66, in wrapper
    handler(message)
  File "/opt/mycroft/skills/cpkodi-skill/__init__.py", line 1162, in handle_channel
    if len(channels) == 0:
TypeError: object of type 'NoneType' has no len()`

I have no idea if this is any relevance for you but, I leave the screen shot of the bug I obtain while asking "Open channel heart TV"
<img width="1280" alt="OpenChannelBug" src="https://user-images.githubusercontent.com/13570586/115725368-15197d00-a382-11eb-943a-6337f2c1998c.png">

**Comment by david-morris** [comment]
Thanks for that info! It looks like you don't have any TV channels set up on Kodi.  If you pull my latest commit, it should just say it can't find the channel.

PVR is the generic term for TiVo.  If you get a kodi addon like IPTV Simple Client and add channels from indexes like the m3us listed [here](https://github.com/iptv-restream/iptv-channels), Kodi gets channels with names and numbers and if you have an EPG source (which I have for German channels but none for Swedish, English, or French) even a TV guide.  Some TV providers also have a way of setting up IPTV for paying customers.

So this code just lets you change the TV channel on Kodi. I figure if you want to record a channel, you'd rather use a non-voice interface to schedule that; I use the voice control when I'm on the couch and want to play something and my hands are greasy.

**Comment by mardub1635** [comment]
Damn that sound great! My partner is german and it is his birthday today,  could not find him a good present  :/. that could make him happy! Can one make mycroft zap kodi on the channel Arte with an EPG?

**Comment by david-morris** [comment]
@mardub1635 I used [this article](https://www.kodi-tipps.de/kodi-iptv-einrichten-live-tv-mit-kodi-anschauen/) to set up my TV initially.  Basically, I used IPTV Simple Client, with http://bit.ly/kn-kodi-tv as my IPTV source and https://ricxepg.nl/epg_data/rytecDE_Basic.gz as my EPG source. 

I get Arte HD with EPG, but maybe there's geoblocking outside of Germany, I wouldn't know.

It's a bit more work to set up, but if you can get [IPTV Merge](https://www.matthuisman.nz/2019/02/iptv-merge-kodi-add-on.html) installed, you can set up both German channels and other channels.

**Comment by mardub1635** [comment]
That is cool! I managed to install it, now it seems to understand something and to even zap. I am not sure if the pvr is supposed to understand the channel number? It does not react to number of the channel "play channel 251" (= "Al Jazeera English" on my kodi TV). The Readme.md helped me though because it hints about the channel names not being the same for kodi vs mycroft. For instance if you say "Play channel Al Jazeera English" mycroft does not find it because it transcribes "al-jazeera english". But if one changes the name of the channel in the channel manager to "al-jazeera english" instead (Yes, it is case sensitive) then it works like a charm!

**Comment by david-morris** [comment]
Thanks for that tip!  I hadn't noticed those issues because I was using low channel numbers which I wasn't changing, and I wasn't trying to open channels by name with my voice.  I updated my pull request for a patch for those issues.

**Comment by mardub1635** [comment]
Happy if it helped! I did not update yet and will let you know once I did, if it worked.

**Comment by pcwii** [comment]
> Happy if it helped! I did not update yet and will let you know once I did, if it worked.
@mardub1635 , Thought I would check in and see if this issue is resolved now?

**Comment by mardub1635** [comment]
Hi
@pcwii the issue is resolved, we can close it.
@david-morris I uninstalled and reinstalled cpkodi  on the latest version of master branch and I managed to change TV channel even with my python 3.7. So your changes seem to work.
Actions done:
```
msm remove cpkodi-skill 
msm install https://github.com/pcwii/cpkodi-skill.git 
```
